### ISSUE TITLE
dot is not needed to access array's element

### ISSUE THREAD

**Issue by YahyaAlfayad** [jalalalawani/week-2-step-3#2]
https://github.com/jalalalawani/week-2-step-3/blob/07dda16882c675fe7f99b3a9859266afebb070bd/hm#L112

to access array elements you don't need to use the dot operator. only use `a[2]` for example.

**Comment by jalalalawani** [comment]
aha , but how can it works if its un needed , shoudnt the dot break the code @YahyaAlfayad  ???
